apiVersion: v1
kind: Pod
metadata:
  name: mysql-test
  labels:
    app: mysql-server
    role: mysql-database
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      command: ["mysqld"]
 
