apiVersion: v1
kind: Pod
metadata:
  name: demo-web4
spec:
  containers:
  - name: envtest
    image: dondamianeo/python_program
    ports:
    - containerPort: 8080
    env:
    - name: STRATEGY_RISK
      valueFrom:
        configMapKeyRef:
          name: simple-configmap
          key: strategy.risk
    - name: STRATEGY_TYPE
      valueFrom:
        configMapKeyRef:
          name: simple-configmap
          key: strategy.type
